__NumPy__

In [1]:
import numpy as np
np.__version__

'1.22.0'

__Typy danych__

In [2]:
l= [1, '2', True, 3.0, None]

In [3]:
[type(item) for item in l]

[int, str, bool, float, NoneType]

In [5]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([4.1, 0, 1, 2, 5])

array([4.1, 0. , 1. , 2. , 5. ])

__Sposoby tworzenia tablic w NumPy__

In [8]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(5, dtype=float)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones((5, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.random.normal(0, 1, (3, 3))

array([[ 0.40914983, -0.64598318, -0.24578549],
       [-0.16792692, -0.93978458, -0.04049244],
       [-0.22804091, -0.11805929,  1.13470803]])

In [14]:
np.random.randint(0, 10, (4, 5))    

array([[8, 7, 8, 3, 5],
       [4, 3, 2, 8, 3],
       [4, 4, 1, 6, 7],
       [6, 3, 8, 7, 2]])

__Operowanie na tablicach w NumPy__

In [18]:
x = np.random.randint(100, size=(2, 3, 4))

In [19]:
x

array([[[36,  8, 22, 39],
        [ 8, 90, 73, 41],
        [57, 99, 75, 77]],

       [[64, 30, 89, 76],
        [ 5, 76, 16, 52],
        [53, 48, 27, 64]]])

In [24]:
print(f"Liczba wymiarów: {x.ndim}")

Liczba wymiarów: 3


In [25]:
print(f"Wymiary: {x.shape}")

Wymiary: (2, 3, 4)


In [26]:
print(f"Rozmiar: {x.size}")

Rozmiar: 24


In [27]:
print(f"Typ w tablicy: {x.dtype}")

Typ w tablicy: int32


In [28]:
print(f"Rozmiar jednego elementu: {x.itemsize} bajtów")

Rozmiar jednego elementu: 4 bajtów


In [29]:
print(f"Rozmiar całej tablicy: {x.nbytes}")

Rozmiar całej tablicy: 96


In [30]:
y=np.arange(10)

In [31]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
y[5]

5

In [33]:
y[0]

0

In [34]:
y[-1]

9

In [37]:
x[0, 1, 2] # element o współrzędnych (0, 1, 2)

73

In [38]:
x[0, 1, 2] = 42

In [39]:
x

array([[[36,  8, 22, 39],
        [ 8, 90, 42, 41],
        [57, 99, 75, 77]],

       [[64, 30, 89, 76],
        [ 5, 76, 16, 52],
        [53, 48, 27, 64]]])

In [40]:
y[0:5]

array([0, 1, 2, 3, 4])

In [41]:
y[:5]

array([0, 1, 2, 3, 4])

In [42]:
y[4:7]

array([4, 5, 6])

In [43]:
x[:1, :, :3]

array([[[36,  8, 22],
        [ 8, 90, 42],
        [57, 99, 75]]])

In [44]:
l1 = [1, 2, 3, 4]
l2 = l1[2:]

In [45]:
l1

[1, 2, 3, 4]

In [46]:
l2

[3, 4]

In [47]:
l2[0]= 66

In [48]:
l2

[66, 4]

In [49]:
l1

[1, 2, 3, 4]

In [53]:
x=np.zeros((2, 3))

In [54]:
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
y= x[0, :]

In [56]:
y

array([0., 0., 0.])

In [58]:
y[0] = 1

In [59]:
y

array([1., 0., 0.])

In [60]:
x

array([[1., 0., 0.],
       [0., 0., 0.]])

In [61]:
x_copy = x[:2, :2].copy()

In [62]:
x_copy[0,0] = 42

In [63]:
x

array([[1., 0., 0.],
       [0., 0., 0.]])

In [65]:
x_copy

array([[42.,  0.],
       [ 0.,  0.]])

__Zmiana wymiarów tablicy__

In [66]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.arange(1, 10).reshape((4, 3))

ValueError: cannot reshape array of size 9 into shape (4,3)

In [68]:
x = np. array([1, 2, 3])

In [70]:
x

array([1, 2, 3])

In [71]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [72]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

__Łączenie tablic__

In [74]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [76]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [77]:
grid = np.array([[1, 2, 3],
               [4, 5, 6]])

In [78]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [81]:
np.vstack([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
np.hstack([grid, grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [83]:
x = np.arange(10)

In [84]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.split(x, [3, 5])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

__Wykonywanie obliczeń na tablicach__

In [86]:
# Funkcja, która liczy nową tablicę z odwrotnościami elementów

In [92]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i, value in enumerate(values):
        output[i] = 1.0 / value
    return output

values = np.random.randint(1, 10, size=5)

In [93]:
values

array([4, 8, 9, 9, 4])

In [94]:
compute_reciprocals(values)

array([0.25      , 0.125     , 0.11111111, 0.11111111, 0.25      ])

In [95]:
big_array = np.random.randint(1, 100, size=1_000_000)

In [96]:
big_array

array([94,  9, 43, ..., 75, 15, 45])

In [97]:
%timeit compute_reciprocals(big_array)

5.07 s ± 157 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [98]:
%timeit 1.0 / big_array

9 ms ± 824 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [99]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
x % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [103]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [104]:
sum(x)

45

In [105]:
%timeit sum(big_array)

172 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [106]:
%timeit np.sum(big_array)

861 µs ± 145 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
