In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.3.5'

In [3]:
pd.Series

pandas.core.series.Series

In [4]:
pd.DataFrame

pandas.core.frame.DataFrame

__Series__

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [6]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
              index=['a', 'b', 'c', 'd'])

In [11]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data['a'] # wyciągnij element o indeksie 'a'

0.25

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index=[2, 3, 5, 7])

In [15]:
data

2    0.25
3    0.50
5    0.75
7    1.00
dtype: float64

In [16]:
population_dict = {
    'California': 38_332_521,
    'Texas': 26_448_193,
    'New York': 19_651_127,
    'Florida': 19_552_860
}

In [18]:
population = pd.Series(population_dict)

In [19]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [20]:
population['California']

38332521

In [21]:
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

__Inne sposoby tworzenia obiektówtypu Series__

In [23]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [24]:
pd.Series(5, index=[1, 2, 3])

1    5
2    5
3    5
dtype: int64

In [25]:
pd.Series({2:'a', 1: 'b', 3: 'c'})

2    a
1    b
3    c
dtype: object

In [26]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

__DataFrame__

In [37]:
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312
}

In [38]:
area = pd.Series(area_dict)

In [39]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
dtype: int64

In [40]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [42]:
states_df = pd.DataFrame({
    'population': population,
    'area': area
})

In [43]:
states_df

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312

In [44]:
states_df.index

Index(['California', 'Texas', 'New York', 'Florida'], dtype='object')

In [45]:
states_df.columns

Index(['population', 'area'], dtype='object')

In [47]:
states_df['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Name: area, dtype: int64

In [49]:
ind = pd.Index([2, 3, 5, 7, 11])

In [50]:
ind[1] = 0

TypeError: Index does not support mutable operations

In [51]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

In [52]:
data

1    a
3    b
5    c
dtype: object

In [53]:
data[1]

'a'

In [55]:
data[1:3] #Zadziałało to tak jak index numpy, jeżeli przekazujemy liczby, to Pandas będzie korzystać z indeksu numpy

3    b
5    c
dtype: object

In [56]:
# loc
# iloc

In [57]:
data.loc[1]

'a'

In [59]:
data.loc[1:3]

1    a
3    b
dtype: object

In [60]:
data.iloc[1]

'b'

In [61]:
data.iloc[1:3]

3    b
5    c
dtype: object

__Wybieranie danych z DataFrame__

In [62]:
states_df

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312

In [63]:
states_df['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Name: population, dtype: int64

In [65]:
states_df['density'] = (states_df['population']/states_df['area']).round(2)

In [73]:
states_df['density'].round(2)

California     90.41
Texas          38.02
New York      139.08
Florida       114.81
Name: density, dtype: float64

In [67]:
states_df[['population', 'density']]

population     density
California    38332521   90.413926
Texas         26448193   38.018740
New York      19651127  139.076746
Florida       19552860  114.806121

In [68]:
states_df['population'] # obiekt typu series

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Name: population, dtype: int64

In [69]:
states_df[['population']] #DataFrame

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860

In [70]:
states_df.iloc[:3, :2]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [71]:
states_df.loc[:'Texas', :'area']

population    area
California    38332521  423967
Texas         26448193  695662

In [74]:
states_df.population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Name: population, dtype: int64

In [76]:
states_df.loc[states_df.density > 100, ['population', 'density']]

# select population, density from states_df where density > 100

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

In [77]:
states_df[states_df.density > 100][['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

__Operowanie na brakujących danych w Pandasie__

In [78]:
None

In [79]:
type(None)

NoneType

In [80]:
vals1=np.array([1, None, 3, 4])

In [81]:
vals1

array([1, None, 3, 4], dtype=object)

In [87]:
for dtype in ['object', 'int']:
    print(f'dtype = {dtype}')
          %timeit np.arange(1E6, dtype=dtype).sum()

IndentationError: unexpected indent (Temp/ipykernel_10492/29259698.py, line 3)

In [88]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [89]:
# np.nan

In [90]:
type(np.nan)

float

In [91]:
vals2 = np.array([1, np.nan, 3, 4])

In [92]:
vals2

array([ 1., nan,  3.,  4.])

In [93]:
1 + np.nan

nan

In [94]:
np.nansum(vals2)

8.0

In [95]:
np.nanmin(vals2)

1.0

In [96]:
np.nanmax(vals2)

4.0

In [97]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [98]:
data = pd. Series([1, np.nan, 'hello', None])

In [99]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [100]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [101]:
data.dropna()

0        1
2    hello
dtype: object

In [102]:
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object

In [104]:
data.fillna(method='backfill')

0        1
1    hello
2    hello
3     None
dtype: object

In [ ]:
Łączenie dataFrames

In [105]:
def make_df(cols, ind):
    data = {c: [f'{c}{i}' for i in ind]
            for c in cols}
    return pd.DataFrame(data, index=ind)

In [106]:
make_df('ABC', ['0', '1', '2'])

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [107]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

In [108]:
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [109]:
pd.concat([df1, df2], axis=1)

A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

In [110]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [111]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

In [112]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [113]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [114]:
pd.merge(df1, df2)

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [115]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})

In [116]:
pd.merge(df1, df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [117]:
pd.merge(df1, df2, on='employee')
# select * from df1 join df2 on df1.employee = df2.employee

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [119]:
pd.merge?

In [120]:
df1 = make_df('AB', [1, 2, 4])
df2 = make_df('ABCD', [1, 2, 5, 6])

In [121]:
df1

A   B
1  A1  B1
2  A2  B2
4  A4  B4

In [122]:
df2

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
5  A5  B5  C5  D5
6  A6  B6  C6  D6

In [123]:
join_types = ['left', 'right', 'outer', 'inner']

In [124]:
for how in join_types:
    print(f'df1 {how} join df2')
    print(pd.merge(df1, df2, on='A', how=how))
    print('-'*10)

df1 left join df2
    A B_x  B_y    C    D
0  A1  B1   B1   C1   D1
1  A2  B2   B2   C2   D2
2  A4  B4  NaN  NaN  NaN
----------
df1 right join df2
    A  B_x B_y   C   D
0  A1   B1  B1  C1  D1
1  A2   B2  B2  C2  D2
2  A5  NaN  B5  C5  D5
3  A6  NaN  B6  C6  D6
----------
df1 outer join df2
    A  B_x  B_y    C    D
0  A1   B1   B1   C1   D1
1  A2   B2   B2   C2   D2
2  A4   B4  NaN  NaN  NaN
3  A5  NaN   B5   C5   D5
4  A6  NaN   B6   C6   D6
----------
df1 inner join df2
    A B_x B_y   C   D
0  A1  B1  B1  C1  D1
1  A2  B2  B2  C2  D2
----------


In [125]:
for how in join_types:
    print(f'df1 {how} join df2')
    print(pd.merge(df1, df2, on=['A', 'B'], how=how))
    print('-'*10)

df1 left join df2
    A   B    C    D
0  A1  B1   C1   D1
1  A2  B2   C2   D2
2  A4  B4  NaN  NaN
----------
df1 right join df2
    A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A5  B5  C5  D5
3  A6  B6  C6  D6
----------
df1 outer join df2
    A   B    C    D
0  A1  B1   C1   D1
1  A2  B2   C2   D2
2  A4  B4  NaN  NaN
3  A5  B5   C5   D5
4  A6  B6   C6   D6
----------
df1 inner join df2
    A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
----------
