__NumPy__

In [1]:
import numpy as np
np.__version__

'1.22.0'

__Typy danych__

In [2]:
l= [1, '2', True, 3.0, None]

In [3]:
[type(item) for item in l]

[int, str, bool, float, NoneType]

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([4.1, 0, 1, 2, 5])

array([4.1, 0. , 1. , 2. , 5. ])

__Sposoby tworzenia tablic w NumPy__

In [6]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(5, dtype=float)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((5, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.random.normal(0, 1, (3, 3))

array([[-0.16077509, -0.52354139, -0.23185698],
       [-0.83351218, -0.380309  ,  0.27613514],
       [ 1.18039085, -1.21427205, -1.02830128]])

In [12]:
np.random.randint(0, 10, (4, 5))    

array([[8, 3, 4, 1, 0],
       [5, 3, 6, 6, 8],
       [2, 9, 8, 0, 4],
       [7, 1, 5, 7, 1]])

__Operowanie na tablicach w NumPy__

In [13]:
x = np.random.randint(100, size=(2, 3, 4))

In [14]:
x

array([[[11, 43, 93, 57],
        [21, 53, 37, 66],
        [71, 72,  7, 67]],

       [[65, 25, 62, 69],
        [13, 47, 99, 98],
        [12, 81, 87, 13]]])

In [15]:
print(f"Liczba wymiarów: {x.ndim}")

Liczba wymiarów: 3


In [16]:
print(f"Wymiary: {x.shape}")

Wymiary: (2, 3, 4)


In [17]:
print(f"Rozmiar: {x.size}")

Rozmiar: 24


In [18]:
print(f"Typ w tablicy: {x.dtype}")

Typ w tablicy: int32


In [19]:
print(f"Rozmiar jednego elementu: {x.itemsize} bajtów")

Rozmiar jednego elementu: 4 bajtów


In [20]:
print(f"Rozmiar całej tablicy: {x.nbytes}")

Rozmiar całej tablicy: 96


In [21]:
y=np.arange(10)

In [22]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
y[5]

5

In [24]:
y[0]

0

In [25]:
y[-1]

9

In [26]:
x[0, 1, 2] # element o współrzędnych (0, 1, 2)

37

In [27]:
x[0, 1, 2] = 42

In [28]:
x

array([[[11, 43, 93, 57],
        [21, 53, 42, 66],
        [71, 72,  7, 67]],

       [[65, 25, 62, 69],
        [13, 47, 99, 98],
        [12, 81, 87, 13]]])

In [29]:
y[0:5]

array([0, 1, 2, 3, 4])

In [30]:
y[:5]

array([0, 1, 2, 3, 4])

In [31]:
y[4:7]

array([4, 5, 6])

In [32]:
x[:1, :, :3]

array([[[11, 43, 93],
        [21, 53, 42],
        [71, 72,  7]]])

In [33]:
l1 = [1, 2, 3, 4]
l2 = l1[2:]

In [34]:
l1

[1, 2, 3, 4]

In [35]:
l2

[3, 4]

In [36]:
l2[0]= 66

In [37]:
l2

[66, 4]

In [38]:
l1

[1, 2, 3, 4]

In [39]:
x=np.zeros((2, 3))

In [40]:
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
y= x[0, :]

In [42]:
y

array([0., 0., 0.])

In [43]:
y[0] = 1

In [44]:
y

array([1., 0., 0.])

In [45]:
x

array([[1., 0., 0.],
       [0., 0., 0.]])

In [46]:
x_copy = x[:2, :2].copy()

In [47]:
x_copy[0,0] = 42

In [48]:
x

array([[1., 0., 0.],
       [0., 0., 0.]])

In [49]:
x_copy

array([[42.,  0.],
       [ 0.,  0.]])

__Zmiana wymiarów tablicy__

In [50]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
np.arange(1, 10).reshape((4, 3))

ValueError: cannot reshape array of size 9 into shape (4,3)

In [52]:
x = np. array([1, 2, 3])

In [53]:
x

array([1, 2, 3])

In [54]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [55]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

__Łączenie tablic__

In [56]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [57]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [58]:
grid = np.array([[1, 2, 3],
               [4, 5, 6]])

In [59]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
np.vstack([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.hstack([grid, grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
x = np.arange(10)

In [65]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.split(x, [3, 5])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

__Wykonywanie obliczeń na tablicach__

In [67]:
# Funkcja, która liczy nową tablicę z odwrotnościami elementów

In [68]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i, value in enumerate(values):
        output[i] = 1.0 / value
    return output

values = np.random.randint(1, 10, size=5)

In [69]:
values

array([4, 2, 7, 4, 2])

In [70]:
compute_reciprocals(values)

array([0.25      , 0.5       , 0.14285714, 0.25      , 0.5       ])

In [71]:
big_array = np.random.randint(1, 100, size=1_000_000)

In [72]:
big_array

array([16, 90, 68, ..., 41,  7, 15])

In [73]:
%timeit compute_reciprocals(big_array)

4.74 s ± 414 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
%timeit 1.0 / big_array

9.3 ms ± 844 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [75]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
x % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [78]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [79]:
sum(x)

45

In [80]:
%timeit sum(big_array)

154 ms ± 17.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [81]:
%timeit np.sum(big_array)

881 µs ± 73 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [85]:
np.min

<function numpy.amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [87]:
M=np.random.randint(10, size=(3,4))

In [88]:
M

array([[2, 5, 4, 7],
       [4, 8, 1, 1],
       [0, 7, 0, 5]])

In [90]:
M.sum(axis=0)

array([ 6, 20,  5, 13])

In [91]:
M.sum(axis=1)

array([18, 14, 12])

__Pórównywanie maski i filtrowanie tablic.__

In [92]:
x= np.array([1, 2, 3, 4, 5])

In [93]:
x<3

array([ True,  True, False, False, False])

In [94]:
x != 3

array([ True,  True, False,  True,  True])

In [95]:
x == 3

array([False, False,  True, False, False])

In [96]:
x>3

array([False, False, False,  True,  True])

In [98]:
np.count_nonzero(x)

5

In [99]:
# ile elementów w tablicy jest mniejszych niż 3?
np.count_nonzero(x<3)

2

In [102]:
x = np.random.randint(10, size=(4, 4))

In [104]:
x

array([[8, 1, 5, 3],
       [4, 7, 3, 3],
       [9, 1, 5, 2],
       [4, 6, 3, 7]])

In [106]:
# Ile wartości w każdym wierszu jest mniejsze niż 6?
np.sum(x<6, axis=1)

array([3, 3, 3, 2])

In [107]:
np.any(x<0)

False

In [108]:
x

array([[8, 1, 5, 3],
       [4, 7, 3, 3],
       [9, 1, 5, 2],
       [4, 6, 3, 7]])

In [110]:
x[x < 5] # Wyjmij te elementy z x, które są mniejsze niż 5

array([1, 3, 4, 3, 3, 1, 2, 4, 3])

In [113]:
x[x < 5] = 0 # wyzeruj elementy, które są mniejsze niż 5

In [114]:
x

array([[8, 0, 5, 0],
       [0, 7, 0, 0],
       [9, 0, 5, 0],
       [0, 6, 0, 7]])

__Fancy indexing__

In [115]:
x = np.random.randint(100, size=10)

In [116]:
x

array([84, 41, 46, 38, 71, 37, 74, 90, 43, 71])

In [119]:
np.array([x[3], x[7], x[2]])

array([38, 90, 46])

In [121]:
# Fancy indexing
ind = [3, 7 , 2]
x[ind]

array([38, 90, 46])

In [122]:
x[[3, 7, 2]]

array([38, 90, 46])

In [124]:
ind = np.array([[3, 7],
            [4, 5]])

In [125]:
x[ind]

array([[38, 90],
       [71, 37]])

In [126]:
x = np.random.randint(100, size=(5, 5))

In [127]:
x

array([[12, 38, 98, 75, 79],
       [68, 84, 53, 40, 11],
       [44, 32, 27, 28, 47],
       [82, 65, 29, 87, 23],
       [14, 85, 79, 52, 69]])

In [128]:
x[2, [0, 1, 2]]

array([44, 32, 27])

In [129]:
x[1:, [2, 0, 1]]

array([[53, 68, 84],
       [27, 44, 32],
       [29, 82, 65],
       [79, 14, 85]])

In [130]:
x[[1, 2], [1, 3]]

array([84, 28])

In [131]:
np.diagonal(x)

array([12, 84, 27, 87, 69])

__Sortowanie__

In [132]:
x = np.random.randint(100, size = 5)

In [133]:
x

array([19,  0, 19, 98, 40])

In [134]:
np.sort(x)

array([ 0, 19, 19, 40, 98])

In [137]:
i= np.argsort(x)

In [138]:
x[i]

array([ 0, 19, 19, 40, 98])

In [139]:
x = np.random.randint(100, size=(5,5))

In [140]:
x

array([[40, 71,  5, 22, 61],
       [14, 42, 74, 12, 87],
       [80, 19, 80, 83, 52],
       [62, 32, 83,  7, 56],
       [79, 95,  4, 54, 23]])

In [141]:
np.sort(x)

array([[ 5, 22, 40, 61, 71],
       [12, 14, 42, 74, 87],
       [19, 52, 80, 80, 83],
       [ 7, 32, 56, 62, 83],
       [ 4, 23, 54, 79, 95]])

 1. Wygeneruj tablicę 100 liczb całkowitych od 0 do 10 i wybierz z niej elementy nieparzyste.


In [144]:
x= np.random.randint(11, size= 100)

In [145]:
x

array([ 2,  3,  4,  2,  8,  1,  6,  8,  9,  2,  8,  4,  1,  5,  6,  2,  2,
        2,  4,  2,  4,  3,  7,  7,  5,  8,  9,  1,  5,  7,  1,  8,  8,  5,
        0,  1,  2,  9,  5,  2,  9, 10,  2,  4,  3,  4,  2,  4,  1,  3,  3,
        1,  9,  6,  5,  4,  8,  3,  4,  2,  0,  7,  9,  5,  5, 10,  5,  6,
        4,  9, 10,  8,  6,  0,  0,  7,  8,  5, 10,  7,  1,  4,  7,  5,  7,
        7, 10,  6,  1, 10,  0,  5,  3,  0,  2,  3,  3,  9,  3,  6])

In [147]:
x[x%2 == 1]

array([3, 1, 9, 1, 5, 3, 7, 7, 5, 9, 1, 5, 7, 1, 5, 1, 9, 5, 9, 3, 1, 3,
       3, 1, 9, 5, 3, 7, 9, 5, 5, 5, 9, 7, 5, 7, 1, 7, 5, 7, 7, 1, 5, 3,
       3, 3, 9, 3])

2. Korzystając z tablicy z poprzedniego zadania zastąp elementy nieparzyste zerami.

In [148]:
x[x%2 ==1] = 0

In [149]:
x

array([ 2,  0,  4,  2,  8,  0,  6,  8,  0,  2,  8,  4,  0,  0,  6,  2,  2,
        2,  4,  2,  4,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  8,  8,  0,
        0,  0,  2,  0,  0,  2,  0, 10,  2,  4,  0,  4,  2,  4,  0,  0,  0,
        0,  0,  6,  0,  4,  8,  0,  4,  2,  0,  0,  0,  0,  0, 10,  0,  6,
        4,  0, 10,  8,  6,  0,  0,  0,  8,  0, 10,  0,  0,  4,  0,  0,  0,
        0, 10,  6,  0, 10,  0,  0,  0,  0,  2,  0,  0,  0,  0,  6])

 3. W jaki sposób zastąpić elementy nieparzyste zerami, ale bez zmieniania oryginalnej tablicy?

In [160]:
x= np.random.randint(11, size= 100)

In [161]:
x

array([ 7,  1,  7,  2,  0, 10,  4,  5, 10,  8,  6,  7, 10,  7,  1,  0,  3,
        1,  3,  1,  3,  2, 10, 10,  7,  2,  1,  9,  4,  0,  1,  3,  3,  0,
       10,  7,  4,  4,  6,  5,  7,  3,  8,  9,  4,  3,  0,  7, 10,  9, 10,
        1,  6,  0,  1,  5,  8,  0,  4,  0,  8,  4,  3,  0,  5,  9,  4,  3,
        5,  2,  5, 10, 10,  2,  8,  3,  7,  7,  1,  2, 10,  6,  0,  8,  1,
        0,  7,  8,  5,  4, 10,  8,  3,  0,  6,  0,  9,  3, 10,  1])

In [162]:
x_copy = x.copy()

In [163]:
x_copy[x_copy%2 == 1] = 0

In [164]:
x_copy

array([ 0,  0,  0,  2,  0, 10,  4,  0, 10,  8,  6,  0, 10,  0,  0,  0,  0,
        0,  0,  0,  0,  2, 10, 10,  0,  2,  0,  0,  4,  0,  0,  0,  0,  0,
       10,  0,  4,  4,  6,  0,  0,  0,  8,  0,  4,  0,  0,  0, 10,  0, 10,
        0,  6,  0,  0,  0,  8,  0,  4,  0,  8,  4,  0,  0,  0,  0,  4,  0,
        0,  2,  0, 10, 10,  2,  8,  0,  0,  0,  0,  2, 10,  6,  0,  8,  0,
        0,  0,  8,  0,  4, 10,  8,  0,  0,  6,  0,  0,  0, 10,  0])

 4. Wygenerować tablicę wypełnioną liczbami losowymi z przedziału 0-100 o wymiarach 3x3 i wybrać elementy większe niż 20 i mniejsze niż 50.


In [170]:
x= np.random.randint(101, size=(3, 3))

In [171]:
x

array([[71,  3, 86],
       [51, 25, 91],
       [ 3, 84, 90]])

In [172]:
x[(x>20)&(x<50)]

array([25])

5. Wygeneruj tablicę o wymiarach 10x10 i stwórz nową tablicę, która ma odwróconą kolejność wierszy.

In [175]:
x= np.random.randint(50, size=(10,10))

In [176]:
x

array([[20, 37,  1, 14, 15, 30, 34, 26, 14,  7],
       [34,  8,  2, 18, 48, 34, 46, 40, 41, 33],
       [ 1, 13, 13, 11,  9, 41,  9,  6, 17, 24],
       [ 7,  7,  8, 33, 40,  5, 20, 22, 14, 17],
       [ 4, 15,  4, 22, 28,  9, 33, 49, 33, 37],
       [31,  9,  2,  0,  8, 24, 15, 46, 33, 39],
       [25, 46, 38, 49, 16, 28, 46, 47, 21,  5],
       [14,  6, 41, 47,  4,  0, 35, 22, 11,  1],
       [ 2,  8, 18,  9, 26, 23, 31,  5, 48, 38],
       [27,  1, 27, 13, 29, 26, 44, 44, 35, 45]])

In [178]:
x[::-1,:]

array([[27,  1, 27, 13, 29, 26, 44, 44, 35, 45],
       [ 2,  8, 18,  9, 26, 23, 31,  5, 48, 38],
       [14,  6, 41, 47,  4,  0, 35, 22, 11,  1],
       [25, 46, 38, 49, 16, 28, 46, 47, 21,  5],
       [31,  9,  2,  0,  8, 24, 15, 46, 33, 39],
       [ 4, 15,  4, 22, 28,  9, 33, 49, 33, 37],
       [ 7,  7,  8, 33, 40,  5, 20, 22, 14, 17],
       [ 1, 13, 13, 11,  9, 41,  9,  6, 17, 24],
       [34,  8,  2, 18, 48, 34, 46, 40, 41, 33],
       [20, 37,  1, 14, 15, 30, 34, 26, 14,  7]])

In [179]:
x[::-1,::-1]

array([[45, 35, 44, 44, 26, 29, 13, 27,  1, 27],
       [38, 48,  5, 31, 23, 26,  9, 18,  8,  2],
       [ 1, 11, 22, 35,  0,  4, 47, 41,  6, 14],
       [ 5, 21, 47, 46, 28, 16, 49, 38, 46, 25],
       [39, 33, 46, 15, 24,  8,  0,  2,  9, 31],
       [37, 33, 49, 33,  9, 28, 22,  4, 15,  4],
       [17, 14, 22, 20,  5, 40, 33,  8,  7,  7],
       [24, 17,  6,  9, 41,  9, 11, 13, 13,  1],
       [33, 41, 40, 46, 34, 48, 18,  2,  8, 34],
       [ 7, 14, 26, 34, 30, 15, 14,  1, 37, 20]])